# Site settings
title_left    : "alper"
title_right   : "s"
description   : "technical & intellectual writings"
keywords      : "software, engineering"
url           : https://alpers.github.io
baseurl       : ""
cover         : "" # logo/cover image uri

google_analytics  : G-VJGJSP3DZE
twitter_username  : ""
comments_enabled  : false
disqus_shortname  : ""
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Alper M."

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "thinkspace.gemspec"
